services:
  - type: web
    name: after-dark
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server_all.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
